# Generated by Django 5.0 on 2023-12-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50)),
                ('add_task', models.ManyToManyField(to='TaskModel.taskmodel')),
            ],
        ),
    ]
