# Generated by Django 5.0 on 2023-12-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='add_task',
        ),
    ]
