# Generated by Django 5.0 on 2023-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0002_remove_taskcategory_add_task'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='add_cat',
            field=models.ManyToManyField(to='TaskCategory.taskcategory'),
        ),
    ]
