# Generated by Django 5.0 on 2023-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0002_taskmodel_add_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Task_Assign_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
